### ISSUE TITLE
object 'which_pls' not found

### ISSUE THREAD

**Issue by amandacpac** [leighseverson/purexposure#6]
I am trying to run the `calculate_exposure` function and keep getting the following error: 

> Error in nrow(which_pls) : object 'which_pls' not found

I was looking through the code, and line 265 of the 04-calculate.R code is where which_pls is first called, but, it looks like some code prior to that that defined it has been deleted. I could be totally wrong, but, a colleague tried running it this function (using the example in the documentation - see below) as well, and got the same error. Any help on this would be greatly appreciated!

```
clean_pur <- readRDS(system.file("extdata", "fresno_clean.rds",
                                 package = "purexposure"))
```
```
fresno_spdf <- readRDS(system.file("extdata", "fresno_spdf.rds",
                                   package = "purexposure"))
```
```
exposure_list <- calculate_exposure(clean_pur, location = "-120.098794, 36.532866",
                                    radius = 3000, spdf = fresno_spdf)
```

**Comment by leighseverson** [comment]
thanks for the heads up! fixed with a few commits on 8/11
